# Balance Bot Configuration Data.

base:
    path:
        logs: 'logs'
        log_config: '/home/pi/Balance_Bot/configs/balance_bot_logging_config.yml'
        ninedof_sensor_calibration: '/home/pi/Balance_Bot/configs/bno055_calibration_config.yml'
    wheel:
        left:
            motor:
                fwd: "GPIO4"    # Physical Pin  7 (1, 4)
                rwd: "GPIO17"   # Physical Pin 11 (1, 6)
                max_value: 1
                min_value: -1
            encoder: "GPIO26"      # Physical Pin 37 (1, 19)

        right:
            motor:
                rwd: "GPIO27"   # Physical Pin 13 (1, 7)
                fwd: "GPIO22"   # Physical Pin 15 (1, 8)
                max_value: 1
                min_value: -1
            encoder: "GPIO21"   # Physical Pin 40 (2, 20)
        power: "GPIO14"         # Physical Pin 8

    arm:
        left:
            motor:
                lift: "GPIO5"   # Physical Pin 29 (1, 15)
                drop: "GPIO6"   # Physical Pin 31 (1, 16)
                max_value: 1
                min_value: -1
            encoder: "GPIO20"   # Physical Pin 38 (2, 19)
        right:
            motor:
                lift: "GPIO13"  # Physical Pin 33 (1, 17)
                drop: "GPIO19"  # Physical Pin 35 (1, 18)
                max_value: 1
                min_value: -1
            encoder: "GPIO16"   # Physical Pin 36 (2, 18)
        power: "GPIO15"         # Physical Pin 10

    # SENSOR_PIN = "GPIO12"     # Physical Pin 32 (2, 16)

    bno055_sensor:
        restore_calibration_available: False

    duration:
        control_update: 50  # milliseconds
        params_update: 1  # seconds
        max_time_step: 60  # seconds
        sensor_history: 600  # seconds
        encoder_sensor_update: 1  # seconds

    pid_param:
        k_proportional: -0.5   # Proportional Constant
        k_integral: 1        # Help catch-up
        k_derivative: 0     # Damping Adjustment. Should be negative

dev:
    motor_encoder_test_sequence: 'motor_encoder_test_sequence.csv'
