# Formatters that are assigned to outputs ("handlers") below
base:
    format:
        simple: "{now:%Y-%m-%d %H:%M:%S}:{event_type}{level_text}:{message}"

    # Outputs, one or more of which can be assigned to loggers
    handler:
        console:
            formatter: simple
            stream: sys.stdout
        log_file:
            formatter: simple
            folder: logs
            filename: debug.log
            maxBytes: 20485760  # 20 MB

        position_history_file:
            formatter: simple
            folder: logs
            filename: position_history.csv
