# Formatters that are assigned to outputs ("handlers") below
base:
    format:
        simple: f"{now:%Y-%m-%d %H:%M}:{event_type}{level_text}:{message}"

    # Outputs, one or more of which can be assigned to loggers
    handler:
        console:
            formatter: simple
            stream: sys.stdout

        log_file:
            formatter: simple
            filename: logs/debug.log
            maxBytes: 20485760  # 20 MB
