# Balance Box Calibration for bno055 Sensor

accel_offset:
    x: 7
    y: 67
    z: -18

magnet_offset:
    x: 645
    y: -169
    z: -210

gyro_offset:
    x: -4
    y: -3
    z: 0

accel_radius: 1000

magnet_radius: 835
